# Hypridle Configuration

general {
    lock_cmd = kill -STOP $(pidof mpvpaper) 2>/dev/null || true; hyprlock; kill -CONT $(pidof mpvpaper) 2>/dev/null || true
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Screen dimming (3 mins)
listener {
    timeout = 180
    on-timeout = brightnessctl set 10%
    on-resume = brightnessctl set 100%
}

# Auto lockscreen (5 mins)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Screen off (8 mins)
listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend PC (15 mins)
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
