-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL E1914H X0T4K42BAT1U",
  mode = "1366x768@59.79",
  position = "1920x312",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GIGABYTE G24F 22110B007656",
  mode = "1920x1080@165.00",
  position = "0x0",
  scale = 1,
  vrr = 1,
  sdr_min_luminance = 0.19,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GIGABYTE G24F 22110B007656", persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GIGABYTE G24F 22110B007656", persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GIGABYTE G24F 22110B007656", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GIGABYTE G24F 22110B007656", persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GIGABYTE G24F 22110B007656", persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "desc:Dell Inc. DELL E1914H X0T4K42BAT1U", persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:Dell Inc. DELL E1914H X0T4K42BAT1U", persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:Dell Inc. DELL E1914H X0T4K42BAT1U", persistent = true })
hl.workspace_rule({ workspace = "9", monitor = "desc:Dell Inc. DELL E1914H X0T4K42BAT1U", persistent = true })
hl.workspace_rule({ workspace = "10", monitor = "desc:Dell Inc. DELL E1914H X0T4K42BAT1U", persistent = true })
