-- Generated by nwg-displays on 2026-06-28 at 18:41:50. Do not edit manually.

hl.workspace_rule({
    workspace = "2",
    monitor = "DP-3",
    default = true
})
hl.workspace_rule({
    workspace = "1",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-2",
    default = true
})
hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-2"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-2"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-2"
})
